---
abstract: 'Interface to Google Buzz API.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  HTTP::Request: 1.40
  LWP::UserAgent: 2.33
  Readonly: 0
  Test::More: 0
  URI::Escape: 3.29
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-Buzz
provides:
  WWW::Google::Buzz:
    file: lib/WWW/Google/Buzz.pm
    version: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
